### ISSUE TITLE
suggestions to the blog.php

### ISSUE THREAD

**Issue by jackbielinski** [pixdoet/blog.php#1]
> BEFORE YOU INSTALL: This is only for my personal website. If you really plan to deploy this yourself, you'll need to change a lot of stuff unless your name is Ian Hiew.

make a config file or something that allows you to just change one string and it applies it to everywhere that says ian hiew

**Comment by nycr1te** [comment]
you should add preview buttojn on manage.,php to do the awesome sauce (the awesonme sauce of course as in       previewing the blog conjtent before the posting)

**Comment by jackbielinski** [comment]
nevermind
